version: '3'
services:

  postgres:
    image: postgres:12
    container_name: icebreaker_postgres
    networks:
      - database
    restart: unless-stopped
    environment:
      - POSTGRES_DB=icebreaker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 6700:5432

  backend:
    image: icebreakerscience/backend:develop
    container_name: icebreaker_backend
    depends_on:
      - postgres
    networks:
      - database
      - backend
    restart: unless-stopped
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://icebreaker_postgres:5432/icebreaker
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - ICEBREAKER_JWTSECRET=secret
      - MEDIA_DIR=/home/media/
    volumes:
      - ./media:/home/media

  frontend:
    image: icebreakerscience/frontend:develop
    container_name: icebreaker_frontend
    depends_on:
      - backend
    networks:
      - frontend
    restart: unless-stopped

  nginx:
    image: nginx
    container_name: icebreaker_nginx
    depends_on:
      - frontend
      - backend
    networks:
      - frontend
      - backend
    restart: unless-stopped
    ports:
      - "12100:80"
    volumes:
      - ./nginx-icebreaker.conf:/etc/nginx/conf.d/default.conf
      - ./media:/home/media

networks:
  frontend:
  backend:
  database:
