version: '3'
services:

  postgres:
    image: postgres:12
    container_name: icebreaker_postgres
    networks:
      - database
    restart: unless-stopped
    environment:
      - POSTGRES_DB=icebreaker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 6700:5432

  backend:
    image: icebreakerscience/backend:develop
    container_name: icebreaker_backend
    depends_on:
      - postgres
    networks:
      - database
      - backend
    restart: unless-stopped
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://icebreaker_postgres:5432/icebreaker
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - ICEBREAKER_JWTSECRET=secret
      - MEDIA_DIR=/home/media/
      - ICEBREAKER_NEO4J_HOST=neo4j
      - ICEBREAKER_NEO4J_PORT=7687
    volumes:
      - ./media:/home/media

  frontend:
    image: icebreakerscience/frontend:develop
    container_name: icebreaker_frontend
    depends_on:
      - backend
    networks:
      - frontend
    restart: unless-stopped

  nginx:
    image: nginx
    container_name: icebreaker_nginx
    depends_on:
      - frontend
      - backend
    networks:
      - frontend
      - backend
    restart: unless-stopped
    ports:
      - "12100:80"
    volumes:
      - ./nginx-icebreaker.conf:/etc/nginx/conf.d/default.conf
      - ./media:/home/media

  neo4j:
    image: neo4j:latest
    container_name: icebreaker_neo4j
    restart: unless-stopped
    networks:
      database:
        aliases:
          - neo4j
    ports:
      - 12220:7474  # HTTP / Web interface
      - 12221:7687  # Bolt
    environment:
      NEO4J_AUTH: neo4j/elsa  # The username cannot be changed.
    volumes:
      - ./neo4j_data:/data
      - ./neo4j_import:/import

networks:
  frontend:
  backend:
  database:
